apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: building-login-back
spec:
    template:
        metadata:
            labels:
                app: building-login-back
        spec:
            containers:
                - name: building-login-back
                  image: redis
                  volumeMounts:
                      - name: redis-data
                        mountPath: /data
                  ports:
                      - containerPort: 6379
                        name: redis
                  command: ["redis-server"]
                  args: ["--appendonly yes"]
            volumes:
                - name: redis-data
                  persistentVolumeClaim:
                      claimName: azurefile
