apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: building-login-front
  namespace: default
spec:
  minReadySeconds: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: building-login-front
    spec:
      containers:
      - env:
        - name: REDIS
          value: building-login-back
        image: pittcontainerreg.azurecr.io/building-login:b0b7407
        name: building-login-front
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
        volumeMounts:
        - mountPath: /building_logs
          name: building-logs
      volumes:
      - name: building-logs
        persistentVolumeClaim:
          claimName: azurefile
