apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: default
spec:
  minReadySeconds: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - image: pittcontainerreg.azurecr.io/hello-world-app:298b0be
        name: hello-world-app
