apiVersion: extensions/v1beta1 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: pittcontainerreg.azurecr.io/jenkins-docker:v13
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins-home
          subPath: jenkins
        - name: docker-sock
          mountPath: /var/run
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: azurefile
      - name: docker-sock
        hostPath:
            path: /var/run
